org.slf4j.simpleLogger.defaultLogLevel=error
org.slf4j.simpleLogger.log.org.hibernate=error
org.slf4j.simpleLogger.log.org.hibernate.SQL=off
org.slf4j.simpleLogger.log.org.hibernate.orm.jdbc.bind=off
org.slf4j.simpleLogger.showDateTime=false
org.slf4j.simpleLogger.showThreadName=false
org.slf4j.simpleLogger.showLogName=false
org.slf4j.simpleLogger.showShortLogName=true
